name: toast_lift
description: Beautiful animated toast notifications for Flutter apps with modern UI and smooth animations.
version: 1.0.1

homepage: https://github.com/Sakshi-2508/toast_lift
repository: https://github.com/Sakshi-2508/toast_lift
issue_tracker: https://github.com/Sakshi-2508/toast_lift/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter: